-- Neuraltale E-Commerce Database Seed Data

-- Drop existing tables if they exist
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;

-- Create Category table
CREATE TABLE "Category" (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT
);

-- Create Product table
CREATE TABLE "Product" (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  "shortDescription" TEXT NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL,
  "compareAtPrice" INTEGER,
  "stockQuantity" INTEGER DEFAULT 0,
  sizes TEXT[] NOT NULL,
  colors TEXT[] NOT NULL,
  images JSONB NOT NULL,
  "techHighlights" JSONB,
  "boxContents" JSONB,
  "productFeatures" JSONB,
  "technicalSpecs" JSONB,
  certifications JSONB,
  "isHeroProduct" BOOLEAN DEFAULT false,
  "heroOrder" INTEGER,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
  "categorySlug" TEXT NOT NULL,
  CONSTRAINT "Product_categorySlug_fkey" FOREIGN KEY ("categorySlug") REFERENCES "Category"(slug) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Create indexes for better performance
CREATE INDEX "Product_categorySlug_idx" ON "Product"("categorySlug");
CREATE INDEX "Product_isHeroProduct_idx" ON "Product"("isHeroProduct");
CREATE INDEX "Product_heroOrder_idx" ON "Product"("heroOrder");

-- Insert Categories
INSERT INTO "Category" (name, slug, description) VALUES
('Smartphones', 'smartphones', 'Latest flagship smartphones with cutting-edge technology'),
('Laptops', 'laptops', 'High-performance laptops for work and gaming'),
('Tablets', 'tablets', 'Versatile tablets for productivity and entertainment'),
('Audio', 'audio', 'Premium headphones, earbuds, and speakers'),
('Wearables', 'wearables', 'Smartwatches and fitness trackers'),
('Gaming', 'gaming', 'Gaming laptops, consoles, and accessories'),
('Accessories', 'accessories', 'Chargers, cases, and tech accessories'),
('Smart Home', 'smart-home', 'Smart home devices and IoT products'),
('Cameras', 'cameras', 'Professional and consumer cameras'),
('Storage', 'storage', 'External drives and storage solutions');

-- Insert Products
INSERT INTO "Product" (
  name, 
  slug,
  "shortDescription", 
  description, 
  price,
  "compareAtPrice",
  "stockQuantity",
  colors, 
  sizes,
  images, 
  "categorySlug",
  "isHeroProduct",
  "heroOrder"
) VALUES
-- Hero Products (Featured on Homepage)
(
  'iPhone 16 Pro Max',
  'iphone-16-pro-max',
  'The ultimate iPhone with titanium design and A18 Pro chip.',
  'Experience the pinnacle of smartphone technology with the iPhone 16 Pro Max. Featuring a stunning 6.7-inch Super Retina XDR display, revolutionary A18 Pro chip, advanced camera system with 48MP main, ultra-wide, and telephoto lenses. Titanium design, USB-C connectivity, and all-day battery life.',
  119999,
  129999,
  50,
  ARRAY['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
  ARRAY['256GB', '512GB', '1TB'],
  '{"Natural Titanium": ["/products/iphone-16-pro-natural-1.jpg", "/products/iphone-16-pro-natural-2.jpg"], "Blue Titanium": ["/products/iphone-16-pro-blue-1.jpg"], "White Titanium": ["/products/iphone-16-pro-white-1.jpg"], "Black Titanium": ["/products/iphone-16-pro-black-1.jpg"]}',
  'smartphones',
  true,
  1
),
(
  'MacBook Pro 14" M4',
  'macbook-pro-14-m4',
  'Supercharged for pros with M4 chip and Liquid Retina XDR display.',
  'The MacBook Pro 14-inch with M4 chip delivers groundbreaking performance and battery life. Features stunning Liquid Retina XDR display, up to 32GB unified memory, advanced thermal design, comprehensive connectivity including Thunderbolt 5, HDMI, and SD card slot. Perfect for developers, creators, and professionals.',
  199999,
  219999,
  30,
  ARRAY['Space Black', 'Silver'],
  ARRAY['16GB RAM 512GB SSD', '24GB RAM 1TB SSD', '32GB RAM 2TB SSD'],
  '{"Space Black": ["/products/macbook-pro-14-black-1.jpg", "/products/macbook-pro-14-black-2.jpg"], "Silver": ["/products/macbook-pro-14-silver-1.jpg"]}',
  'laptops',
  true,
  2
),
(
  'AirPods Pro (3rd Gen)',
  'airpods-pro-3rd-gen',
  'Premium wireless earbuds with advanced active noise cancellation.',
  'AirPods Pro (3rd generation) feature adaptive audio that adjusts noise control based on your environment. USB-C charging, improved H2 chip for better sound quality, enhanced Find My features with precision finding, and up to 6 hours of listening time. Water and sweat resistant (IPX4).',
  24999,
  NULL,
  100,
  ARRAY['White'],
  ARRAY['Standard'],
  '{"White": ["/products/airpods-pro-3-1.jpg", "/products/airpods-pro-3-2.jpg"]}',
  'audio',
  true,
  3
),
(
  'iPad Pro 12.9"',
  'ipad-pro-12-9',
  'The ultimate iPad experience with M4 chip and stunning display.',
  'iPad Pro 12.9-inch powered by the M4 chip delivers desktop-class performance in a thin, light design. Features Liquid Retina XDR display with ProMotion, 12MP Wide camera, LiDAR Scanner, Face ID, and all-day battery life. Works seamlessly with Apple Pencil Pro and Magic Keyboard.',
  129999,
  139999,
  40,
  ARRAY['Space Gray', 'Silver'],
  ARRAY['256GB WiFi', '512GB WiFi', '1TB WiFi', '256GB WiFi+Cellular'],
  '{"Space Gray": ["/products/ipad-pro-gray-1.jpg", "/products/ipad-pro-gray-2.jpg"], "Silver": ["/products/ipad-pro-silver-1.jpg"]}',
  'tablets',
  true,
  4
),
(
  'Apple Watch Ultra 3',
  'apple-watch-ultra-3',
  'The most rugged and capable Apple Watch for extreme conditions.',
  'Apple Watch Ultra 3 is designed for endurance athletes, outdoor adventurers, and water sports enthusiasts. Features titanium case, the brightest Apple display, precision dual-frequency GPS, up to 36 hours of battery life, dive computer, and extensive health monitoring including ECG, blood oxygen, and temperature sensing.',
  79999,
  NULL,
  60,
  ARRAY['Natural Titanium'],
  ARRAY['49mm'],
  '{"Natural Titanium": ["/products/watch-ultra-3-1.jpg", "/products/watch-ultra-3-2.jpg", "/products/watch-ultra-3-3.jpg"]}',
  'wearables',
  true,
  5
),

-- Regular Products
(
  'Samsung Galaxy S24 Ultra',
  'samsung-galaxy-s24-ultra',
  'Flagship Android phone with S Pen and 200MP camera.',
  'Samsung Galaxy S24 Ultra combines cutting-edge AI features with professional-grade photography. Features 6.8-inch Dynamic AMOLED display, Snapdragon 8 Gen 3, 200MP camera system, built-in S Pen, and 5000mAh battery with fast charging. Titanium frame construction.',
  129999,
  139999,
  45,
  ARRAY['Titanium Gray', 'Titanium Black', 'Titanium Violet'],
  ARRAY['256GB', '512GB', '1TB'],
  '{"Titanium Gray": ["/products/s24-ultra-gray-1.jpg"], "Titanium Black": ["/products/s24-ultra-black-1.jpg"], "Titanium Violet": ["/products/s24-ultra-violet-1.jpg"]}',
  'smartphones',
  false,
  NULL
),
(
  'Dell XPS 15',
  'dell-xps-15',
  'Premium Windows laptop with stunning OLED display.',
  'Dell XPS 15 delivers exceptional performance for creative professionals. Features 15.6-inch 4K OLED touchscreen, Intel Core i9 processor, NVIDIA GeForce RTX 4070, up to 64GB RAM, and all-day battery life. CNC machined aluminum chassis with carbon fiber palm rest.',
  189999,
  209999,
  25,
  ARRAY['Platinum Silver', 'Graphite'],
  ARRAY['16GB RAM 512GB SSD', '32GB RAM 1TB SSD', '64GB RAM 2TB SSD'],
  '{"Platinum Silver": ["/products/xps-15-silver-1.jpg"], "Graphite": ["/products/xps-15-graphite-1.jpg"]}',
  'laptops',
  false,
  NULL
),
(
  'Sony WH-1000XM5',
  'sony-wh-1000xm5',
  'Industry-leading noise canceling headphones with premium sound.',
  'Sony WH-1000XM5 headphones feature industry-leading noise cancellation, exceptional sound quality with LDAC support, 30-hour battery life, and AI-powered call quality. Comfortable design with soft fit leather for all-day wear. Multipoint connection for seamless device switching.',
  39999,
  44999,
  80,
  ARRAY['Black', 'Silver'],
  ARRAY['Standard'],
  '{"Black": ["/products/sony-xm5-black-1.jpg", "/products/sony-xm5-black-2.jpg"], "Silver": ["/products/sony-xm5-silver-1.jpg"]}',
  'audio',
  false,
  NULL
),
(
  'iPad Air 11"',
  'ipad-air-11',
  'Powerful, colorful, and versatile iPad with M2 chip.',
  'iPad Air 11-inch with M2 chip delivers incredible performance in a thin, light design. Features Liquid Retina display, 12MP Wide camera, landscape front camera, and Touch ID. Compatible with Magic Keyboard and Apple Pencil Pro. Available in vibrant colors.',
  59999,
  64999,
  70,
  ARRAY['Space Gray', 'Starlight', 'Purple', 'Blue'],
  ARRAY['128GB WiFi', '256GB WiFi', '128GB WiFi+Cellular'],
  '{"Space Gray": ["/products/ipad-air-gray-1.jpg"], "Starlight": ["/products/ipad-air-starlight-1.jpg"], "Purple": ["/products/ipad-air-purple-1.jpg"], "Blue": ["/products/ipad-air-blue-1.jpg"]}',
  'tablets',
  false,
  NULL
),
(
  'Samsung Galaxy Watch 7',
  'samsung-galaxy-watch-7',
  'Advanced health and fitness tracking with Wear OS.',
  'Samsung Galaxy Watch 7 combines comprehensive health monitoring with smart connectivity. Features advanced sleep tracking, body composition analysis, heart rate monitoring, GPS, and up to 40 hours of battery life. Runs Wear OS with access to Google apps.',
  34999,
  39999,
  90,
  ARRAY['Green', 'Cream', 'Silver'],
  ARRAY['40mm', '44mm'],
  '{"Green": ["/products/galaxy-watch-7-green-1.jpg"], "Cream": ["/products/galaxy-watch-7-cream-1.jpg"], "Silver": ["/products/galaxy-watch-7-silver-1.jpg"]}',
  'wearables',
  false,
  NULL
),
(
  'ASUS ROG Zephyrus G16',
  'asus-rog-zephyrus-g16',
  'Ultra-slim gaming laptop with RTX 4090 and ROG Nebula display.',
  'ASUS ROG Zephyrus G16 is the ultimate gaming laptop for performance enthusiasts. Features 16-inch ROG Nebula Display (2.5K 240Hz), Intel Core i9, NVIDIA GeForce RTX 4090, 32GB DDR5 RAM, and advanced cooling system. Ultra-slim 1.95cm profile.',
  279999,
  299999,
  15,
  ARRAY['Eclipse Gray'],
  ARRAY['32GB RAM 1TB SSD', '64GB RAM 2TB SSD'],
  '{"Eclipse Gray": ["/products/rog-g16-1.jpg", "/products/rog-g16-2.jpg"]}',
  'gaming',
  false,
  NULL
),
(
  'Google Pixel 9 Pro',
  'google-pixel-9-pro',
  'AI-powered photography and pure Android experience.',
  'Google Pixel 9 Pro delivers the best of Google AI in a premium smartphone. Features 6.7-inch LTPO OLED display, Google Tensor G4 chip, advanced AI camera system with Magic Editor, and 7 years of OS updates. Exceptional computational photography.',
  99999,
  109999,
  55,
  ARRAY['Obsidian', 'Porcelain', 'Hazel'],
  ARRAY['256GB', '512GB'],
  '{"Obsidian": ["/products/pixel-9-pro-obsidian-1.jpg"], "Porcelain": ["/products/pixel-9-pro-porcelain-1.jpg"], "Hazel": ["/products/pixel-9-pro-hazel-1.jpg"]}',
  'smartphones',
  false,
  NULL
),
(
  'Bose QuietComfort Ultra Earbuds',
  'bose-qc-ultra-earbuds',
  'Premium wireless earbuds with spatial audio and noise cancellation.',
  'Bose QuietComfort Ultra Earbuds deliver world-class noise cancellation and immersive audio. Features CustomTune technology, Immersive Audio with head tracking, up to 6 hours battery life, and comfortable StayHear Max tips. IPX4 water resistance.',
  29999,
  NULL,
  75,
  ARRAY['Black', 'White Smoke'],
  ARRAY['Standard'],
  '{"Black": ["/products/bose-qc-ultra-black-1.jpg"], "White Smoke": ["/products/bose-qc-ultra-white-1.jpg"]}',
  'audio',
  false,
  NULL
),
(
  'MagSafe Charger',
  'magsafe-charger',
  'Fast wireless charging for iPhone with perfect alignment.',
  'Official Apple MagSafe Charger provides up to 25W of fast wireless charging for iPhone 16 models. Magnetic alignment ensures perfect placement every time. Compatible with Qi2-enabled devices. Includes 2m USB-C cable.',
  3999,
  NULL,
  200,
  ARRAY['White'],
  ARRAY['Standard'],
  '{"White": ["/products/magsafe-charger-1.jpg"]}',
  'accessories',
  false,
  NULL
),
(
  'Samsung 1TB Portable SSD T9',
  'samsung-ssd-t9',
  'Ultra-fast portable storage with USB 3.2 Gen 2x2.',
  'Samsung Portable SSD T9 delivers blazing-fast speeds up to 2,000 MB/s. Features rugged design with dynamic thermal guard, hardware encryption, and compact form factor. Perfect for content creators and photographers.',
  14999,
  16999,
  120,
  ARRAY['Black'],
  ARRAY['1TB', '2TB', '4TB'],
  '{"Black": ["/products/samsung-t9-1.jpg"]}',
  'storage',
  false,
  NULL
),
(
  'HomePod (2nd Gen)',
  'homepod-2nd-gen',
  'Immersive smart speaker with Spatial Audio and Siri.',
  'HomePod delivers rich, immersive audio with spatial awareness and computational audio. Features temperature and humidity sensor, Matter smart home hub, hands-free Siri, and seamless integration with Apple devices. Available in Midnight and White.',
  29999,
  NULL,
  65,
  ARRAY['Midnight', 'White'],
  ARRAY['Standard'],
  '{"Midnight": ["/products/homepod-midnight-1.jpg"], "White": ["/products/homepod-white-1.jpg"]}',
  'smart-home',
  false,
  NULL
),
(
  'Sony A7 IV',
  'sony-a7-iv',
  'Full-frame mirrorless camera for hybrid creators.',
  'Sony A7 IV is a versatile full-frame camera perfect for both photography and videography. Features 33MP sensor, 4K 60p video, advanced autofocus with Real-time Eye AF, 5-axis stabilization, and dual card slots. Professional-grade build quality.',
  249999,
  NULL,
  20,
  ARRAY['Black'],
  ARRAY['Body Only', 'With 28-70mm Lens'],
  '{"Black": ["/products/sony-a7iv-1.jpg", "/products/sony-a7iv-2.jpg"]}',
  'cameras',
  false,
  NULL
),
(
  'Razer BlackShark V2 Pro',
  'razer-blackshark-v2-pro',
  'Wireless esports gaming headset with THX Spatial Audio.',
  'Razer BlackShark V2 Pro delivers competition-grade audio performance. Features THX Spatial Audio, HyperSpeed Wireless, titanium-coated 50mm drivers, and detachable mic. Up to 70 hours of battery life. Designed for professional esports players.',
  17999,
  19999,
  85,
  ARRAY['Black'],
  ARRAY['Standard'],
  '{"Black": ["/products/razer-blackshark-1.jpg"]}',
  'gaming',
  false,
  NULL
),
(
  'Anker 100W USB-C Charger',
  'anker-100w-charger',
  'Compact 4-port GaN charger for all your devices.',
  'Anker 737 Charger features advanced GaN technology in a compact design. Three USB-C ports and one USB-A port deliver up to 100W total power. Charge laptops, tablets, and phones simultaneously. Includes ActiveShield 2.0 for temperature monitoring.',
  7999,
  NULL,
  150,
  ARRAY['Black'],
  ARRAY['Standard'],
  '{"Black": ["/products/anker-737-1.jpg"]}',
  'accessories',
  false,
  NULL
),
(
  'LG 27" UltraGear OLED Gaming Monitor',
  'lg-27-ultragear-oled',
  '240Hz OLED gaming monitor with 0.03ms response time.',
  'LG UltraGear 27GR95QE-B features stunning OLED technology with true blacks and infinite contrast. 240Hz refresh rate, 0.03ms response time, NVIDIA G-SYNC compatible, and HDR10 support. Perfect for competitive gaming and content creation.',
  99999,
  109999,
  30,
  ARRAY['Black'],
  ARRAY['27 inch'],
  '{"Black": ["/products/lg-oled-monitor-1.jpg"]}',
  'gaming',
  false,
  NULL
);